### ISSUE TITLE
Missing commands from W3C specification

### ISSUE THREAD

**Issue by andrewnicols** [php-webdriver/php-webdriver#683]
I've just been through the spec document comparing to the actions in the HttpCommandExecutor. The following commands defined in the W3C specification are currently missing:

- [x] 11.7 Switch to Parent Frame #718
`POST  /session/{session id}/frame/parent`
- [x] 11.8.4 Minimize Window #719
`POST  /session/{session id}/window/minimize`
- [x] 11.8.5 Fullscreen Window #720
`POST  /session/{session id}/window/fullscreen`
- [x] 14.2 Get Named Cookie #717 
`GET  /session/{session id}/cookie/{name}`
- [ ] 15.6 Release Actions #755 
`DELETE  /session/{session id}/actions`
- [x] 17.2 Take Element Screenshot #701 
`GET  /session/{session id}/element/{element id}/screenshot`

Source: https://www.w3.org/TR/webdriver/
Ref. #469

**Comment by OndraM** [comment]
@andrewnicols Thanks for the overview. Do you have an idea about the opposite case - ie. commands which were implemented in JsonWire OSS protocol and are not part of W3C specification?

**Comment by andrewnicols** [comment]
Thanks @OndraM ,

I guess that depends on the way we want to approach things generally.

You've started to mark JSONWire-only exceptions as deprecated, so I'd suggest that's would be most consistent but I assume they'll be deprecated and never removed to support testing of older non-W3C browsers.

I feel an exception is the only sane way to go.

**Comment by OndraM** [comment]
You are right, nothing won't be removed in php-webdriver 1.x.

However they will be removed in php-webdriver 2.0, as it will support only W3C WebDriver. See #657 for ongoing discussion about scope php-webdriver 2.0.


The reason I marked those exceptions deprecated is to announce users this is something they will need to change in the future (ie. they depend on behavior which will be removed in next major version). Also by marking them deprecated, it will be easier to distinguish what should be removed once we create branch for 2.0 :).

**Comment by andrewnicols** [comment]
Perhaps a new Exception for `W3CNotImplemented` or `NotImplementedbyDriver` for those then?

**Comment by OndraM** [comment]
@andrewnicols I'm not sure I understand - where would you use those exceptions?

**Comment by OndraM** [comment]
@andrewnicols BTW take element screenshot is already implemented here - do you think we can use this PR? https://github.com/facebook/php-webdriver/pull/515

**Comment by andrewnicols** [comment]
> @andrewnicols I'm not sure I understand - where would you use those exceptions?
So there is no intent to release another version of php-webdrvier 1.x which supports both? When we're happy with the level of support for W3C, we'll remove all JSONWire support and release 2.0?

If there is to be any release of the 1.x branch which supports both JSONWire and W3C then it may make sense to throw an Exception when a W3C-only feature is used by a JSONWire client.

> @andrewnicols BTW take element screenshot is already implemented here - do you think we can use this PR? #515

I'll take a look at that PR and comment on there. Thanks for pointing it out.

**Comment by andrewnicols** [comment]
I've just pushed a branch to my repo which adds:
1. switch to parent frame
1. minimize
1. maximize

I'm half-way through getNamedCookie, and then I'll look at release actions.

If you have a chance to look at my branch @OndraM and give any feedback that'd be much appreciated.
https://github.com/facebook/php-webdriver/compare/community...andrewnicols:missingCommands?expand=1

I'll finish off the remaining commands tomorrow and submit for PR.

**Comment by andrewnicols** [comment]
I encountered this bug with chromium/chromedriver relating to the minimize command which prevents test confirmations: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3275

**Comment by OndraM** [comment]
@andrewnicols Feel free to submit those as a PR - it will be easier for me to have a look and comment :). But it looks great, thanks :ok_hand: 

Also please send at least the getNamedCookie as standalone PR (ie. without the minimize/maximize stuff), in order to test and discus it separately.

**Comment by OndraM** [comment]
:ballot_box_with_check:  Get named cookie is being added by #717 .

**Comment by andrewnicols** [comment]
Not quite sure how best to implement the release Actions command.
I was thinking to add a new `release` function into `lib/Interactions/WebDriverActions.php` but there's already a `release` function in there to release mouse buttons.

Thoughts?

**Comment by OndraM** [comment]
> Not quite sure how best to implement the release Actions command.
> I was thinking to add a new `release` function into `lib/Interactions/WebDriverActions.php` but there's already a `release` function in there to release mouse buttons.
> 
> Thoughts?

Do we need this endpoint? It is not replacing the current release method, right?

I'm thinking about targeting it into 2.0 milestone - if there is not an usecase and need in 1.8. What do you think, @andrewnicols?

**Comment by OndraM** [comment]
Release Actions separated to issue #755 & closing this one.
