### ISSUE TITLE
Annoucement: upcoming branch renaming

### ISSUE THREAD

**Issue by OndraM** [php-webdriver/php-webdriver#739]
As the Packagist package was renamed, it is now a good time to make branch renaming together, so that people could update their composer.json only once.

Historically, `master` branch was dedicated archived legacy version of the library from the times when Facebook actively used the library. This branch will be renamed to `legacy`. If you used master branch, you will need to update your composer.json like this:

```diff
"require": {
-    "php-webdriver/webdriver": "dev-master",
+    "php-webdriver/webdriver": "dev-legacy",
}
```

Community development was happening on `community` branch. This branch will soon be moved to `master`. So if you depends on community branch, this is what you will need to do in composer.json:

```diff
"require": {
-    "php-webdriver/webdriver": "dev-community",
+    "php-webdriver/webdriver": "dev-master",
}
```

If you depend on version constrain (what is recommended), like ` "php-webdriver/webdriver": "^1.7.0"`, only make sure you depend on `php-webdriver/webdriver` and not `facebook/webdriver` (see https://github.com/php-webdriver/php-webdriver/issues/730#issuecomment-575601572).

### TODO
- [x] Push current `master` branch as `legacy` branch
- [x] Delete `master` branch and push current `community` branch as new `master` branch
- [x] Update repository settings to set `master` branch as the main one
- [x] Update mentions of community branch in docs, CONTRIBUTING.md atd. (#740)
- [x] Update active PRs to point to `master` branch instead of `community` branch
- [x] Delete `community` branch
- [x] Delete `dev-community` version on Packagist

**Comment by OndraM** [comment]
Renamed :ok_hand:
